# Purpose: Virtual host configuration — this is where the core Nginx setup for this lab was configured.
# What was configured:
# - Nginx listens on port 80 for all incoming HTTP traffic
# - Serves static frontend files (index.nginx-debian.html) from /var/www/html/
# - Reverse proxies all /api/* requests to the Flask API server at 192.168.35.20:5000
# - Passes the original client Host header and real IP address to the Flask API

server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location /api/ {
		proxy_pass http://192.168.35.20:5000/; #Trailing slash ensures /api/trades --> /trades on backend
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

}
