# Purpose: Virtual host configuration — this is where the core Nginx setup for this lab is configured.
# What was configured:
# - Nginx listens on port 80 for all incoming HTTP traffic
# - Serves static frontend files (index.nginx-debian.html) from /var/www/html/
# - Reverse proxies all /api/* requests to the Flask API server at 192.168.35.20:5000
# - Passes the original client Host header and real IP address to the Flask API

```nginx
server {
    listen 80 default_server;           # Listen on port 80 (HTTP)
    listen [::]:80 default_server;      # Listen on IPv6 as well
    
    root /var/www/html;                 # Root directory for static files
    index index.html index.htm index.nginx-debian.html;  # Default file
    server_name _;                      # Match any hostname
    
    # Rule 1: Serve static files
    location / {
        try_files $uri $uri/ =404;      # Try file, then directory, else 404
    }
    
    # Rule 2: Reverse proxy API requests
    location /api/ {
        proxy_pass http://192.168.35.20:5000/;     #Trailing slash ensures /api/ is stripped --> /trades on backend
        proxy_set_header Host $host;			   #Preserve host header
        proxy_set_header X-Real-IP $remote_addr;   #Preserve client's real IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  #Record proxy chain
    }
}
```
