# PostgreSQL Configuration File
# This file controls how PostgreSQL listens for connections and performs

listen_addresses = '*'    #Listen on all network interfaces (allows connections from other machines)

port = 5432               #Port to listen on (default)
